version: '3.8'
services:
    whatsapp-http-api:
        image: devlikeapro/whatsapp-http-api
        ports:
            - 3000:3000
        stdin_open: true
        tty: true
        container_name: whatsapp-http-api
        restart: always
        environment:
            WHATSAPP_HOOK_URL: "http://bot:5000/bot"
            WHATSAPP_HOOK_EVENTS: "*"
    bot:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./app:/app
        environment:
            - DB_HOST=mongo
            - DB_PORT=27017
            - WAAPI_URL=http://whatsapp-http-api:3000
        ports:
            - "5000:5000"
        container_name: bot
        restart: unless-stopped
        hostname: bot
    mongo:
        image: mongo:4.4.6-bionic
        container_name: mongo

        volumes:
            - ./data/db:/data/db
        ports:
            - "27017:27017"
        restart: unless-stopped
        hostname: mongo
    mongo-express:
        image: mongo-express:0.54.0
        container_name: mongo-express
        restart: unless-stopped
        ports:
            - "8081:8081"
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_MONGODB_PORT: 27017
        #      ME_CONFIG_SITE_BASEURL: /
        #      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
        depends_on:
            - mongo